name: ChYing build

on:
  create:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare release environment
    runs-on: ubuntu-latest
    steps:
      - run: env
  build-gui:
    name: Build gui
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            output: ChYing.exe
          - os: macos-latest
            platform: darwin/universal
            # wails bug, mac 的 output file 不生效, 先用这个保证能用
            output: ChYing
          - os: ubuntu-latest
            platform: linux/amd64
            output: ChYing-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install && npm run build
        working-directory: frontend
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.output }}
          build-platform: ${{ matrix.platform }}
          go-version: 1.19
          package: false
      - if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -rf ./build/bin/${{ matrix.output }}.app.zip
          ditto -c -k --keepParent ./build/bin/${{matrix.output}}.app ./build/bin/${{matrix.output}}.app.zip
          rm -rf ./build/bin/${{ matrix.output }}.app

      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: build/bin/*

  collect-release:
    name: Collect and release
    needs: [ build-gui ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - run: ls -al target && ls -R target/
      - working-directory: target
        run: |
          rm -rf ChYing-amd64-installer.exe
          rm -rf ChYing.pkg
          mv ChYing.app.zip ChYing-darwin.app.zip
      - run: ls -al target && ls -R target/ && file target/
      - uses: actions/upload-artifact@v3
        with:
          name: target-release
          path: target/*

      # release assets
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*
      # 提交 commit 信息 到 release
      - name: Get latest release tag
        id: get_latest_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await context.github.repos.listReleases(context.repo);
            const releaseTag = data[0].tag_name;
            console.log(`Latest release tag: ${releaseTag}`);
            return releaseTag;
        output-to: latest_release_tag

      - name: Get commit messages since last release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Latest release tag: ${{ steps.get_latest_release.outputs.latest_release_tag }}"
          echo "$(git log --no-decorate --pretty=format:'- %s' "${{ steps.get_latest_release.outputs.latest_release_tag }}..HEAD")"
        id: get_commit_messages
        shell: bash

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changelog

            ${{
               steps.get_commit_messages.outputs.get_commit_messages
            }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@latest
        with:
          files: target/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
